### ISSUE TITLE
ValueError: could not convert string to float: chrX-19961845-19963954-FBtr0070000-2109-+

### ISSUE THREAD

**Issue by yancychy** [genemine/iread#9]
Hi, when I ran iread, the output file is as follows.

The output of IB296_input-3.cutadapt_intron_reads.txt is like this:
chrX    19961845        19963954        FBtr0070000     2109    +       chrX-19961845-19963954-FBtr0070000-2109-+       0
       0       0.000000
chrX    19964071        19964781        FBtr0070000     710     +       chrX-19964071-19964781-FBtr0070000-710-+        0
       0       0.000000

The error is ;
Traceback (most recent call last):
  File "/data/iread/assess_intron.py", line 52, in <module>
    icounts   = float(table[6])
ValueError: could not convert string to float: chrX-19961845-19963954-FBtr0070000-2109-+

Thanks.

**Comment by genemine** [comment]
Hi there,


&nbsp; &nbsp; My student Zhenpeng (cced here) will help you on this issue.


Best,
Hongdong






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "genemine/iread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月22日(星期六) 上午10:18
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[genemine/iread] ValueError: could not convert string to float: chrX-19961845-19963954-FBtr0070000-2109-+ (Issue #9)





 
Hi, when I ran iread, the output file is as follows.
 
The output of IB296_input-3.cutadapt_intron_reads.txt is like this:
 chrX    19961845        19963954        FBtr0070000     2109    +       chrX-19961845-19963954-FBtr0070000-2109-+       0
 0       0.000000
 chrX    19964071        19964781        FBtr0070000     710     +       chrX-19964071-19964781-FBtr0070000-710-+        0
 0       0.000000
 
The error is ;
 Traceback (most recent call last):
 File "/data/iread/assess_intron.py", line 52, in 
 icounts   = float(table[6])
 ValueError: could not convert string to float: chrX-19961845-19963954-FBtr0070000-2109-+
 
Thanks.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yancychy** [comment]
Ok. Thanks. 
I changed the index of array in the assess_intron.py line 51-56. But all intron framgent count are 0.  

#1      3207317 3213438 ENSMUSG00000051951      6121    1-3207317-3213438-ENSMUSG00000051951-6121       0       0       0.000000
fo.write('intron_id\tfragments\tjunction_reads\tfpkm\tentropy_score\ttotal_fragments\tretention_at_given_cutoff\n')
for line in f:
        if line[0] != '#':
                table = line.strip().split('\t')
                ilength   = float(table[4])
                icounts   = float(table[7])
                ijunction = float(table[8])
                ientropy  = round(float(table[9]),6)
                ifpkm = round(1000000000*icounts/(ilength + bias)/total_reads,2)
                cnt= [table[6],table[7],table[8],str(ifpkm),str(ientropy),str(total_reads)]
                if ifpkm >= fpkm and ientropy >= entropy and ijunction >= n_junction and icounts >= n_reads:
                        cnt.append('yes')
                else:
                        cnt.append('no')
                fo.write('\t'.join(cnt)+'\n')

f.close()
fo.close()

os.system('rm '+intron_reads_file)

**Comment by yancychy** [comment]
Another question is 
-t specifies the totally number of mapped reads, 
Here, mapped read meaning the unique aligned read + mulitple aligned reads? 
My output is as following:
intron_id       fragments       junction_reads  fpkm    entropy_score   total_fragments retention_at_given_cutoff
chrX-19961845-19963954-FBtr0070000_FBgn0031081-2109-+   0       0       0.0     0.0     100000000.0     no
chrX-19964071-19964781-FBtr0070000_FBgn0031081-710-+    0       0       0.0     0.0     100000000.0     no
chrX-19964944-19965005-FBtr0070000_FBgn0031081-61-+     0       0       0.0     0.0     100000000.0     no
chrX-19965126-19965196-FBtr0070000_FBgn0031081-70-+     0       0       0.0     0.0     100000000.0     no

**Comment by Zhen-Peng-Wu** [comment]
@yancychy  Hi, one potential issue is related the naming of chromosome names. For independent intron file, BAM, GTF file used, please always use '1', '2',.. or 'X', 'Y' as chromosome names, without adding 'chr'. That's, 'chr1' will not work as it is not consistent with the chromosome name in the independent intron file required for iREAD, and thus cannot be recognized.

**Comment by Zhen-Peng-Wu** [comment]
@yancychy  Another, -t specifies the totally number of mapped reads.
 The mapped read  are those that are correctly matched to the reference genome sequence. It is ok if mapped read = the unique aligned read + mulitple aligned reads.

**Comment by yancychy** [comment]
Thanks @Zhen-Peng-Wu . I will remove the "chr" in the input file. But I have another question about "chrUn_CP007071v1" or "chrY_DS485894v1_random". Shoule I remove them? 
Or "Un_CP007071v1" or "Y_DS485894v1_random"?

**Comment by Zhen-Peng-Wu** [comment]
@yancychy  Yes,  you should remove the uncommon chromosomes, such as chrUn_CP007071v1. Common chromosomes contain '1-22, X, Y' chromosomes. Moreover, if you use 'gtftools' to obtain indenpent introns, there are just common chromosomes. Please use 'gtftools' to calculate independent intron (http://www.genemine.org/gtftools.php).

**Comment by yancychy** [comment]
Ok. Thanks.
